---
- name: Installing Apache
  hosts: localhost
  become: yes
  tasks:
  - name: Installing Apache, VIM, GIT, ntp for Debian family
    apt:
     name: "{{ item }}"
     state: present
    with_items:
     - apache2
     - vim
     - git 
     - ntp
    when: ansible_facts['os_family'] == "Debian"
    
  - name: Installing Apache, VIM, GIT, ntp for RedHat family
    yum: 
     name: "{{ item }}"
     state: present
    loop:
     - apache2
     - vim
     - git 
     - ntp
    when: ansible_facts['os_family'] == "RedHat"

  - name: Customising Apache homepage
    lineinfile: 
     path: /home/opstree/Desktop/apache_index.html
     regex: <h1>Welcome to Apache</h1>
     line: <h1>Welcome Yogendra Pratap Singh currently you are using {{ ansible_hostname }}</h1>
    notify: 
     - Restart Apache

  handlers:
  - name: Re-Starting Apache
    service: 
     name: apache2
     state: restarted