---
- name: Create EC2 Instance
  ec2:
    key_name: "{{ aws_key_name }}"
    instance_type: "{{ aws_instance_type }}"
    image: "{{ aws_instance_image }}"
    wait: yes
    region: "{{ aws_region }}"
    group_id: "{{ aws_security_groupId }}"
    count: 1
    instance_tags:
       Name: EC2-Ansible
    vpc_subnet_id: "{{ aws_subnetId }}"
    assign_public_ip: yes
