---
# Installing Nginx
- name: Install Nginx on Ubuntu
  apt: 
   name: nginx
   state: present
  when: ansible_facts['os_family'] == "Debian"
- name: Install Nginx on CentOS
  yum:
   name: nginx
   state: present
  when: ansible_facts['os_family'] == "RedHat"
- name: Installation failed
  fail:
   msg: This OS is not Supported by the Role
  when: (ansible_facts['os_family'] != "Debian") and
        (ansible_facts['os_family'] != "RedHat")
